
FROM golang:1.25

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]